require "rails_helper"

RSpec.describe Food do
  it "creates a food poros based on attributes" do
    attr = {
        "fdcId": 477475,
        "description": "SWEET POTATO",
        "lowercaseDescription": "sweet potato",
        "dataType": "Branded",
        "gtinUpc": "20042431",
        "publishedDate": "2019-04-01",
        "brandOwner": "FRESH & EASY",
        "ingredients": "SWEET POTATO, CHIPOTLE CHICKEN {COOKED CHICKEN (CHICKEN BREAST WITH RIB MEAT, CHICKEN BROTH, CONTAINS LESS THAN 2% OF: MODIFIED POTATO STARCH, GARLIC POWDER, CANOLA OIL, SOYBEAN OIL, SALT, SODIUM PHOSPHATE, CHICKEN FAT, FLAVOR), CHIPOTLE MANGO SAUCE [MANGO CHIPOTLE MARINADE (MANGO PUREE, WATER, CHIPOTLE PEPPER, ONION, SALT, BROWN SUGAR, CANOLA OIL, VINEGAR, GARLIC, LEMON JUICE CONCENTRATE, TOMATO PASTE, SPICES, RICE WINE VINEGAR, SUGAR, CILANTRO, CITRIC ACID)], WATER, CILANTRO}, MANGO SALSA (MANGO, CUCUMBER, TOMATO, LIME JUICE, MANGO PUREE, ONION, CILANTRO, SERRANO PEPPERS, SALT).",
        "marketCountry": "United States",
        "foodCategory": "Other Deli",
        "modifiedDate": "2018-01-20",
        "dataSource": "LI",
        "servingSizeUnit": "g",
        "servingSize": 312.0,
        "householdServingFullText": "1 CONTAINER",
        "tradeChannels": [
            "NO_TRADE_CHANNEL"
        ]
        # "allHighlightFields": "<b>Ingredients</b>: <em>SWEET</em> <em>POTATO</em>, CHIPOTLE CHICKEN {COOKED CHICKEN (CHICKEN BREAST WITH RIB MEAT, CHICKEN BROTH",
        # "score": 1259.0756,
        # "microbes": [],
        # "foodNutrients": [
        #     {
        #         "nutrientId": 1087,
        #         "nutrientName": "Calcium, Ca",
        #         "nutrientNumber": "301",
        #         "unitName": "MG",
        #         "derivationCode": "LCCD",
        #         "derivationDescription": "Calculated from a daily value percentage per serving size measure",
        #         "derivationId": 75,
        #         "value": 26.0,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 5300,
        #         "indentLevel": 1,
        #         "foodNutrientId": 3376467,
        #         "percentDailyValue": 8
        #     },
        #     {
        #         "nutrientId": 1089,
        #         "nutrientName": "Iron, Fe",
        #         "nutrientNumber": "303",
        #         "unitName": "MG",
        #         "derivationCode": "LCCD",
        #         "derivationDescription": "Calculated from a daily value percentage per serving size measure",
        #         "derivationId": 75,
        #         "value": 0.58,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 5400,
        #         "indentLevel": 1,
        #         "foodNutrientId": 3376468,
        #         "percentDailyValue": 10
        #     },
        #     {
        #         "nutrientId": 1104,
        #         "nutrientName": "Vitamin A, IU",
        #         "nutrientNumber": "318",
        #         "unitName": "IU",
        #         "derivationCode": "LCCD",
        #         "derivationDescription": "Calculated from a daily value percentage per serving size measure",
        #         "derivationId": 75,
        #         "value": 5290.0,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 7500,
        #         "indentLevel": 1,
        #         "foodNutrientId": 3376469,
        #         "percentDailyValue": 330
        #     },
        #     {
        #         "nutrientId": 1162,
        #         "nutrientName": "Vitamin C, total ascorbic acid",
        #         "nutrientNumber": "401",
        #         "unitName": "MG",
        #         "derivationCode": "LCCD",
        #         "derivationDescription": "Calculated from a daily value percentage per serving size measure",
        #         "derivationId": 75,
        #         "value": 4.8,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 6300,
        #         "indentLevel": 1,
        #         "foodNutrientId": 3376470,
        #         "percentDailyValue": 25
        #     },
        #     {
        #         "nutrientId": 1003,
        #         "nutrientName": "Protein",
        #         "nutrientNumber": "203",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 5.45,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 600,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933342,
        #         "percentDailyValue": 0
        #     },
        #     {
        #         "nutrientId": 1004,
        #         "nutrientName": "Total lipid (fat)",
        #         "nutrientNumber": "204",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 1.28,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 800,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933343,
        #         "percentDailyValue": 6
        #     },
        #     {
        #         "nutrientId": 1005,
        #         "nutrientName": "Carbohydrate, by difference",
        #         "nutrientNumber": "205",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 16.4,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 1110,
        #         "indentLevel": 2,
        #         "foodNutrientId": 4933344,
        #         "percentDailyValue": 17
        #     },
        #     {
        #         "nutrientId": 1008,
        #         "nutrientName": "Energy",
        #         "nutrientNumber": "208",
        #         "unitName": "KCAL",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 106,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 300,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933345,
        #         "percentDailyValue": 0
        #     },
        #     {
        #         "nutrientId": 2000,
        #         "nutrientName": "Sugars, total including NLEA",
        #         "nutrientNumber": "269",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 4.17,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 1510,
        #         "indentLevel": 3,
        #         "foodNutrientId": 4933346,
        #         "percentDailyValue": 0
        #     },
        #     {
        #         "nutrientId": 1079,
        #         "nutrientName": "Fiber, total dietary",
        #         "nutrientNumber": "291",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 1.9,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 1200,
        #         "indentLevel": 3,
        #         "foodNutrientId": 4933347,
        #         "percentDailyValue": 24
        #     },
        #     {
        #         "nutrientId": 1093,
        #         "nutrientName": "Sodium, Na",
        #         "nutrientNumber": "307",
        #         "unitName": "MG",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 173,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 5800,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933348,
        #         "percentDailyValue": 23
        #     },
        #     {
        #         "nutrientId": 1253,
        #         "nutrientName": "Cholesterol",
        #         "nutrientNumber": "601",
        #         "unitName": "MG",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 14.0,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 15700,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933349,
        #         "percentDailyValue": 15
        #     },
        #     {
        #         "nutrientId": 1257,
        #         "nutrientName": "Fatty acids, total trans",
        #         "nutrientNumber": "605",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 0.0,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 15400,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933350,
        #         "percentDailyValue": 0
        #     },
        #     {
        #         "nutrientId": 1258,
        #         "nutrientName": "Fatty acids, total saturated",
        #         "nutrientNumber": "606",
        #         "unitName": "G",
        #         "derivationCode": "LCCS",
        #         "derivationDescription": "Calculated from value per serving size measure",
        #         "derivationId": 70,
        #         "value": 0.32,
        #         "foodNutrientSourceId": 9,
        #         "foodNutrientSourceCode": "12",
        #         "foodNutrientSourceDescription": "Manufacturer's analytical; partial documentation",
        #         "rank": 9700,
        #         "indentLevel": 1,
        #         "foodNutrientId": 4933351,
        #         "percentDailyValue": 5
        #     }
        # ],
        # "finalFoodInputFoods": [],
        # "foodMeasures": [],
        # "foodAttributes": [],
        # "foodAttributeTypes": [],
        # "foodVersionIds": []
    }

    food = Food.new(attr)

    expect(food).to be_a(Food)
    expect(food.upc).to eq('20042431')
    expect(food.description).to eq("SWEET POTATO")
    expect(food.ingredients).to eq("SWEET POTATO, CHIPOTLE CHICKEN {COOKED CHICKEN (CHICKEN BREAST WITH RIB MEAT, CHICKEN BROTH, CONTAINS LESS THAN 2% OF: MODIFIED POTATO STARCH, GARLIC POWDER, CANOLA OIL, SOYBEAN OIL, SALT, SODIUM PHOSPHATE, CHICKEN FAT, FLAVOR), CHIPOTLE MANGO SAUCE [MANGO CHIPOTLE MARINADE (MANGO PUREE, WATER, CHIPOTLE PEPPER, ONION, SALT, BROWN SUGAR, CANOLA OIL, VINEGAR, GARLIC, LEMON JUICE CONCENTRATE, TOMATO PASTE, SPICES, RICE WINE VINEGAR, SUGAR, CILANTRO, CITRIC ACID)], WATER, CILANTRO}, MANGO SALSA (MANGO, CUCUMBER, TOMATO, LIME JUICE, MANGO PUREE, ONION, CILANTRO, SERRANO PEPPERS, SALT).")
    expect(food.brand).to eq("FRESH & EASY")
  end
end